// // src/components/markup/MarkupTable.jsx
// import React, { useEffect, useRef } from "react";

// /**
//  * MarkupTable
//  * - data-driven DataTable initialization (columns mapping)
//  * - robust cleanup to avoid removeChild errors
//  * - delegates Edit/Delete clicks via callbacks (onEdit/onDelete)
//  */
// export default function MarkupTable({ rules = [], onEdit, onDelete }) {
//   const tableRef = useRef(null);

//   useEffect(() => {
//     const el = tableRef.current;
//     if (!el) return;

//     // safe destroy if present
//     try {
//       if (el._dt && typeof el._dt.destroy === "function") {
//         if (el.isConnected || document.contains(el)) el._dt.destroy();
//         el._dt = null;
//       }
//     } catch (e) {
//       el._dt = null;
//     }

//     if (!window.DataTable) {
//       console.warn("DataTable not found on window.");
//       return;
//     }

//     const columns = [
//       { title: "", data: null, orderable: false, searchable: false, render: () => '<input type="checkbox" />' },
//       {
//         title: "Rule Name",
//         data: "name",
//         render: (data, type, row) => {
//           const sub = row.created ? `<div class="rule-sub">Created: ${row.created}</div>` : "";
//           return `${data} ${sub}`;
//         }
//       },
//       { title: "Type", data: "type", render: (d) => `<span class="badge ${d === "Markup" ? "badge-markup" : "badge-discount"}">${d}</span>` },
//       { title: "Value", data: "value" },
//       { title: "Applied To", data: "appliedTo" },
//       {
//         title: "Services",
//         data: "services",
//         render: (services = []) => services.map(s => `<span class="service-badge">${s}</span>`).join(" ")
//       },
//       { title: "Status", data: "status", render: (s) => `<span class="badge ${s === "Active" ? "badge-status-active" : "badge-status-pending"}">${s}</span>` },
//       {
//         title: "Action",
//         data: null,
//         orderable: false,
//         searchable: false,
//         render: function (data, type, row) {
//           return `<button class="btn btn-sm btn-primary-navy edit-btn" data-id="${row.id}"><i class="bi bi-pencil-square"></i></button>
//                   <button class="btn btn-sm btn-danger delete-btn ms-2" data-id="${row.id}"><i class="bi bi-trash3"></i></button>`;
//         }
//       }
//     ];

//     // map rules to data objects compatible with columns
//     const data = rules.map(r => ({
//       id: r.id,
//       name: r.name,
//       type: r.type,
//       value: r.value,
//       appliedTo: r.appliedTo,
//       services: r.services,
//       status: r.status,
//       created: r.created
//     }));

//     let dt;
//     try {
//       dt = new window.DataTable(el, {
//         data,
//         columns,
//         paging: true,
//         pageLength: 10,
//         lengthMenu: [10, 25, 50, 100],
//         searching: true,
//         ordering: true,
//         info: true
//       });
//       el._dt = dt;
//     } catch (err) {
//       console.error("Failed to init DataTable:", err);
//       return;
//     }

//     // delegated click handler
//     const handler = (e) => {
//       const btn = e.target.closest ? e.target.closest("button") : null;
//       if (!btn) return;
//       if (btn.matches(".edit-btn")) {
//         const id = btn.getAttribute("data-id");
//         if (id) onEdit?.(Number(id));
//       } else if (btn.matches(".delete-btn")) {
//         const id = btn.getAttribute("data-id");
//         if (id) onDelete?.(Number(id));
//       }
//     };

//     el.addEventListener("click", handler);

//     // cleanup
//     return () => {
//       try { el.removeEventListener("click", handler); } catch (e) {}
//       try {
//         if (el._dt && typeof el._dt.destroy === "function") {
//           if (el.isConnected || document.contains(el)) el._dt.destroy();
//           else try { el._dt.destroy(); } catch {}
//         }
//       } catch (err) {
//         console.warn("Error during DataTable destroy:", err);
//       } finally {
//         if (el) el._dt = null;
//       }
//     };
//   }, [rules, onEdit, onDelete]);

//   return (
//     <div className="table-responsive">
//       <table ref={tableRef} id="markupRulesTable" className="table table-striped" style={{ width: "100%" }}>
//         <thead>
//           <tr>
//             <th></th>
//             <th>Rule Name</th>
//             <th>Type</th>
//             <th>Value</th>
//             <th>Applied To</th>
//             <th>Services</th>
//             <th>Status</th>
//             <th>Action</th>
//           </tr>
//         </thead>
//         {/* tbody will be generated by DataTable */}
//         <tbody />
//       </table>
//     </div>
//   );
// }


'use client';

// src/components/markup/MarkupTable.jsx
import React, { useEffect, useRef } from "react";
import CanDisable from "../CanDisable";

/**
 * MarkupTable
 * - data-driven DataTable initialization (columns mapping)
 * - robust cleanup to avoid removeChild errors
 * - delegates Edit/Delete clicks via callbacks (onEdit/onDelete)
 */
export default function MarkupTable({ rules = [], onEdit, onDelete }) {
  const tableRef = useRef(null);

  useEffect(() => {
    const el = tableRef.current;
    if (!el) return;

    // safe destroy if present
    try {
      if (el._dt && typeof el._dt.destroy === "function") {
        if (el.isConnected || document.contains(el)) el._dt.destroy();
        el._dt = null;
      }
    } catch (e) {
      el._dt = null;
    }

    if (!window.DataTable) {
      console.warn("DataTable not found on window.");
      return;
    }

    const columns = [
      { title: "", data: null, orderable: false, searchable: false, render: () => '<input type="checkbox" />' },
      {
        title: "Rule Name",
        data: "name",
        render: (data, type, row) => {
          const sub = row.created ? `<div class="rule-sub">Created: ${row.created}</div>` : "";
          return `${data} ${sub}`;
        }
      },
      { title: "Type", data: "type", render: (d) => `<span class="badge ${d === "Markup" ? "badge-markup" : "badge-discount"}">${d}</span>` },
      { title: "Value", data: "value" },
      { title: "Applied To", data: "appliedTo" },
      {
        title: "Services",
        data: "services",
        render: (services = []) => services.map(s => `<span class="service-badge">${s}</span>`).join(" ")
      },
      { title: "Status", data: "status", render: (s) => `<span class="badge ${s === "Active" ? "badge-status-active" : "badge-status-pending"}">${s}</span>` },
      {
        title: "Action",
        data: null,
        orderable: false,
        searchable: false,
        render: function (data, type, row) {
          // Note: Permission checks are applied in parent page via CanDisable wrapper
          // This shows buttons - actual permission enforcement happens at page level
          return `<button class="btn btn-sm btn-primary-navy edit-btn" data-id="${row.id}"><i class="bi bi-pencil-square"></i></button>
                  <button class="btn btn-sm btn-danger delete-btn ms-2" data-id="${row.id}"><i class="bi bi-trash3"></i></button>`;
        }
      }
    ];

    // map rules to data objects compatible with columns
    const data = rules.map(r => ({
      id: r.id,
      name: r.name,
      type: r.type,
      value: r.value,
      appliedTo: r.appliedTo,
      services: r.services,
      status: r.status,
      created: r.created
    }));

    let dt;
    try {
      dt = new window.DataTable(el, {
        data,
        columns,
        paging: true,
        pageLength: 10,
        lengthMenu: [10, 25, 50, 100],
        searching: true,
        ordering: true,
        info: true
      });
      el._dt = dt;
    } catch (err) {
      console.error("Failed to init DataTable:", err);
      return;
    }

    // delegated click handler
    const handler = (e) => {
      const btn = e.target.closest ? e.target.closest("button") : null;
      if (!btn) return;
      if (btn.matches(".edit-btn")) {
        const id = btn.getAttribute("data-id");
        if (id) onEdit?.(Number(id));
      } else if (btn.matches(".delete-btn")) {
        const id = btn.getAttribute("data-id");
        if (id) onDelete?.(Number(id));
      }
    };

    el.addEventListener("click", handler);

    // cleanup
    return () => {
      try { el.removeEventListener("click", handler); } catch (e) {}
      try {
        if (el._dt && typeof el._dt.destroy === "function") {
          if (el.isConnected || document.contains(el)) el._dt.destroy();
          else try { el._dt.destroy(); } catch {}
        }
      } catch (err) {
        console.warn("Error during DataTable destroy:", err);
      } finally {
        if (el) el._dt = null;
      }
    };
  }, [rules, onEdit, onDelete]);

  return (
    <div className="table-responsive">
      <table ref={tableRef} id="markupRulesTable" className="table table-striped" style={{ width: "100%" }}>
        <thead>
          <tr>
            <th></th>
            <th>Rule Name</th>
            <th>Type</th>
            <th>Value</th>
            <th>Applied To</th>
            <th>Services</th>
            <th>Status</th>
            <th>Action</th>
          </tr>
        </thead>
        {/* tbody will be generated by DataTable */}
        <tbody />
      </table>
    </div>
  );
}
